version: "3.9"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: . # path to Dockerfile
      dockerfile: app/Dockerfile
    container_name: backend_flask_app
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
      FLASK_APP: manage.py
      FLASK_ENV: development

  frontend:
    build: ./static
    container_name: front_end_react_app
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
