name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .                       # Project root as context
          file: ./app/Dockerfile               # Backend Dockerfile path
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:v1

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./static                       # Project root as context
          file: ./static/Dockerfile      # Frontend Dockerfile path (adjust if needed)
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:v1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernets/postgres-deployment.yaml
          kubectl apply -f kubernets/backend-deployment.yaml
          kubectl apply -f kubernets/frontend-deployment.yaml
